spring:
  swagger:
    group:
      user-api:
        group-name: 01.user-api                     # api组的名字，会在swagger-ui的api下拉列表中显示
        title: 用户相关的操作                           # api组的标题，会在swagger-ui的标题处描述
        description: 用户相关的操作，包括用户登录登出         # api组的描述，会在swagger-ui的描述中显示
        base-package: com.test.gitee
        path-regex: /api/user/.*                    # 匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                             # 匹配到的url在swagger中测试请求时加的url前缀
        version: 0.0.0                              # api版本
        license: 该文档仅限公司内部传阅                    # 授权协议
        license-url: '#'                            # 授权协议地址
#        terms-of-service-url:                      # 服务条款地址
        contact:                                    # 文档联系人
          name: 张三丰                                # 联系人名字
          email: zhangsan@team.com                  # 联系人邮箱
          url: http://www.team.com                  # 联系地址
          
      message-api:
        group-name: 02.message-api                  # api组的名字，会在swagger-ui的api下拉列表中显示
        title: 消息相关的操作                            # api组的标题，会在swagger-ui的标题处描述
        description: 消息相关的操作，包括消息发送和列出        # api组的描述，会在swagger-ui的描述中显示
        path-regex: /api/message/.*                 # 匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                             # 匹配到的url在swagger中测试请求时加的url前缀
        version: 0.0.0                              # api版本
        license: 该文档仅限公司内部传阅                    # 授权协议
        license-url: '#'                            # 授权协议地址
#        terms-of-service-url:                      # 服务条款地址
        contact:                                    # 文档联系人
          name: 张三丰                                # 联系人名字
          email: zhangsan@team.com                  # 联系人邮箱
          url: http://www.team.com                  # 联系地址
          
      all-api:
        group-name: 03.all-api                      # api组的名字，会在swagger-ui的api下拉列表中显示
        title: 所有的api                              # api组的标题，会在swagger-ui的标题处描述
        description: 所有的api                        # api组的描述，会在swagger-ui的描述中显示
        base-package: 'com.*controller'
#        path-regex:                                # 匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                             # 匹配到的url在swagger中测试请求时加的url前缀
        version: 0.0.0                              # api版本
        license: 该文档仅限公司内部传阅                    # 授权协议
        license-url: '#'                            # 授权协议地址
#        terms-of-service-url:                      # 服务条款地址
        contact:                                    # 文档联系人
          name: 张三丰                                # 联系人名字
          email: zhangsan@team.com                  # 联系人邮箱
          url: http://www.team.com                  # 联系地址